### ISSUE TITLE
Pc2D_Foster.m, Line 164, Typo?

### ISSUE THREAD

**Issue by bradyh20** [nasa/CARA_Analysis_Tools#3]
Is there a type on line 164 of Pd2D_Foster.m?

I think there is a parenthesis out of position.  Should this:
z0-(sqrt(pi))/2*HBR
instead be this:
z0-(sqrt(pi)/2)*HBR
?

Hope this is helpful.

**Comment by lgbaars** [comment]
Thank you for writing up this issue. Looking at it a little further, it appears that the parenthesis around sqrt(pi) is superfluous. All three of these calculations will produce the same exact results due to the order of operations implemented by Matlab:

1. z0-(sqrt(pi))/2*HBR
   sqrt(pi) gets evaluated first
   then the parenthesis is applied (this doesn't change the value of sqrt(pi))
   sqrt(pi) is divided by 2, then multiplied by HBR
   finally the subtraction between z0 and the previous expression is applied
2. z0-(sqrt(pi)/2)*HBR
   sqrt(pi) gets evaluated first
   the parenthesis forces the "/2" expression to get evaluated next
   this quantity is multiplied by HBR
   finally the subtraction between z0 and the previous expression is applied 
3. z0-sqrt(pi)/2*HBR
   sqrt(pi) gets evaluated first
   sqrt(pi) is divided by 2, then multiplied by HBR
   finally the subtraction between z0 and the previous expression is applied

Notice that in whichever formulation described above, sqrt(pi) gets evaluated first, followed by "/2", and then "*HBR". We could have certainly had a problem if the parenthesis around other portions of the equation. Thank you for taking such a close look at the code. I'll make a note to remove the extra parenthesis from Pc2D_Foster.m for future releases of the code.

**Comment by bradyh20** [comment]
Yeah, I agree it doesn't affect the output, just noticed that it was different than the lines around it.  Thanks again for sharing this code and tests!
