### ISSUE TITLE
Collision Consequence Figures not working.

### ISSUE THREAD

**Issue by Artemis297** [nasa/CARA_Analysis_Tools#4]
Hi, I'm having issues running the collision consequence figures code. I have the values from the collision consequence code itself, however I am only getting errors when running it.
>> CollisionConsequenceFigures
Warning: An Error occured attempting to generate collision consequence plots 
> In CollisionConsequenceFigures (line 267) 

ans =

     0

I thought this may be an issues with the number of pieces generated by the collision but when i reduced that value the same error ocurred. Also Matlab suggest that the variable 'CatastrophicPlotGenerationThreshold' isnt in use, wasn't sure if this was affecting anything. Any help would be appreciated.

**Comment by lgbaars** [comment]
In order to look into this further, we would need to know what input parameters you are using to run this code. Would you be able to provide your values for each of the input parameters listed below?
PrimaryMass
VRel
OutputFolder
OutputID
Catastrophic
NumOfPieces
massVec

**Comment by Artemis297** [comment]
New to using this Matlab code and Github so forgive me if anything is wrong.
Primary Mass = 450
VRel = 14600 m/s
OutputFolder = not specified due to it just being a test run
OutputID = not specified due to above
Catastrophic = Logical, 1
NumOfPieces = 74196
massVec = 1.2091e+03

Let me know if anything else is needed or if i'm doing anything wrong.

**Comment by lgbaars** [comment]
The CollisionConsequenceFigures.m file is intended to be used in conjunction with the outputs from the CollisionConsequenceNumPieces.m and EstimateObjectMassQuantiles.m functions. The "Catastrophic" and "NumOfPieces" arrays are generated by CollisionConsequenceNumPieces.m while the "massVec" array is generated by EstimateObjectMassQuantiles.m. I've updated the documentation within the function in order to better reflect this dependency. In addition, I've added some examples within the comments of the code in order to show exactly how the function should be used.

Note: There are a number of parameters needed in order to generate the massVec, including the unknown secondary object's RCS value, drag coefficient + variance, and ballistic coefficient + variance. These values are not typically available for public use so it would be difficult for a general user to produce a massVec. The values provided in the example (and unit tests) are specific to the Sodium-Potassium (NaK) droplets and should not be used for unknown secondary objects. In order to get around this problem, I've made the "massVec" parameter optional so that the other two graphs can be generated without this vector provided.

If you do know the mass of the primary object, the relative velocity of the conjunction, and the mass of the secondary object, then you shouldn't need to call the CollisionConsequenceFigures.m function. This function should only be used if there are unknowns and will give a user a general idea of the distribution of the number of pieces created in catastrophic and non-catastrophic collisions. When the three input parameters are known, then you can simply call CollisionConsequenceNumPieces.m and it will tell you whether or not the collision is catastrophic and the number of pieces that are expected to be created from the conjunction.

As an extra piece of information regarding how catastrophic conjunctions are categorized:
A collision is categorized as "catastrophic" when exceeds 40,000 Joules/kg. The document "Lechtenberg_2019_Evaluating_Coll_Consequence.pdf" in the References directory at the top-level of this repository goes into further details on the collision consequence implementation. The 40,000 Joules/kg threshold is documented within Johnoson, et. al., "NASA's New Breakup Model of EVOLVE 4.0" wherein a non-catastrophic collision occurs when the smaller object has fragmentation while the larger object has cratering. Catastrophic collisions occur when both the primary and secondary objects experience fragmentation. The CollisionConsequenceNumPieces.m function performs this determination and will estimate the number of pieces generated by the collision.

Please take a look at the updated code and let us know if the modifications/updated documentation has cleared up the issue.

**Comment by Artemis297** [comment]
Thank you for your reply. The changes/explanations input into the code have really helped explain what I needed to do and where I was going wrong. When testing the example 1 test case in CollisionConsequenceFigures, I get this issue:

`[Catastrophic,NumOfPieces] = CollisionConsequenceNumPieces(PrimaryMass,VRel,SecondaryMass);`
`Not enough input arguments.`

`Error in CollisionConsequenceNumPieces (line 69)`
    `NumOfPieces=round(0.1.*BigM.^0.75.*(Lc).^-1.71);`

Lc is the base value of 0.05 in this case.

Also, as you mentioned, in order to generate massVec, RCS, ballistic and drag coefficient are needed. Is there any way at all to get this information? As part of my final year project i'm attempting to model debris and the effects of such collisions with active/inactive spacecraft, so access to that type of information would be very useful for that part and also other sections of my project. Any help would be appreciated in this case. Thanks for your help!

**Comment by lgbaars** [comment]
Double check to make sure that you are using the most up-to-date version of CollisionConsequenceNumPieces.m. That line of code does not appear at the same line number (line 69) in any of my historic versions of the code. In our first posting of the code, that line appeared on line 67 of the source code. The 2nd modification add the Lc parameter is an optional parameter that defaults to 0.05. The line of code you posted should appear on line 73. I am able to run both examples without any errors or warnings displayed.

Unfortunately we do not have the ability to release any of the RCS, ballistic coefficient, or drag coefficient data publicly. However, if you are working on project for school, you might be able just to use some of the parameters provided within the EstimateObjectMassQuantiles_UnitTest.m. That file has examples for several NaK spheres as well as 6U and 1U cubesats. Just pick something close to the size of your simulated debris and you should be good to go.

If that doesn't work for you, then you can use the NASA_SEM_SizeVecToRCS.m to estimate a starting RCS value for the estimated size of your simulated debris object. You'll have to select your own ballistic coefficient and drag parameters. Cd and CdVar can have a default value of 2.7 and (0.05*Cd)^2 for an unknown object. Ballistic coefficient will be dependent on orbital altitude. Best bet is just to use one of the ballistic coefficients from the unit test file. You can play around with it until you get a reasonable range of masses from the graphing routine.

**Comment by Artemis297** [comment]
Thanks, just needed to use the updated code. I'll attempt to use the examples provided as RCS and coefficient values and see how that goes. If that doesn't work then I'll use the other method suggested. Thank you for your help and input. This may be asking too much, but is it possible that someone could write a small or short explanation of what the graphs produced are showing? Absolutely fine if not as I understand you're probably busy. Thanks for your help thus far!

**Comment by lgbaars** [comment]
The top graphs are histograms counting the number of values displayed on the x-axis. The bottom graphs are the empirical cumulative distribution functions (eCDFs) of the same data. Google searches should help with deciphering an eCDF. I will now close this issue considering that the fix seems to have resolved the problem. Thank you for reaching out and good luck with your project.
